name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  check:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache: true

      - name: lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
        run: make lint
